"""remove_actividad_estado_table

Revision ID: 2cf36b9bbc35
Revises: b1969da54c8d
Create Date: 2026-01-24 16:21:17.857903

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2cf36b9bbc35'
down_revision: Union[str, None] = 'b1969da54c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actividad_estado')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividad_estado',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('id_juego', sa.VARCHAR(length=36), nullable=False),
    sa.Column('id_actividad', sa.VARCHAR(length=36), nullable=False),
    sa.Column('fecha_inicio', sa.DATETIME(), nullable=False),
    sa.Column('duracion', sa.INTEGER(), nullable=True),
    sa.Column('fecha_fin', sa.DATETIME(), nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), nullable=False),
    sa.Column('puntuacion_total', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['id_actividad'], ['actividad.id'], ),
    sa.ForeignKeyConstraint(['id_juego'], ['juego.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
